CREATE DATABASE DebtManager_db
GO

USE DebtManager_db
GO

CREATE TABLE Users
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(255) NOT NULL
);
GO

CREATE TABLE Debts
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Name VARCHAR(200) NOT NULL,
    OriginalAmount DECIMAL(18,2) NOT NULL,
    CurrentBalance DECIMAL(18,2) NOT NULL,
    InterestRate DECIMAL(5,2) NOT NULL,
    MonthlyPayment DECIMAL(18,2) NOT NULL,
    StartDate DATETIME NOT NULL,
    DueDate DATETIME NOT NULL,
    CONSTRAINT FK_Debts_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);
GO

CREATE TABLE Payments
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    DebtId UNIQUEIDENTIFIER NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    PaymentDate DATETIME NOT NULL,
    CONSTRAINT FK_Payments_Debts FOREIGN KEY (DebtId) REFERENCES Debts(Id)
);
GO

CREATE TABLE RefreshTokens
(
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    TokenHash VARCHAR(128) NOT NULL,
    ExpiresAt DATETIME NOT NULL,
    IsRevoked BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME NOT NULL,
    RevokedAt DATETIME NULL,
    CONSTRAINT FK_RefreshTokens_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);
GO

ALTER TABLE Users
ADD PasswordHash VARCHAR(255) NOT NULL DEFAULT '';
GO